# Generated by Django 5.1.1 on 2025-11-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('buyer', 'Comprador')], default='buyer', max_length=10),
        ),
    ]
