# Generated by Django 5.1.1 on 2025-11-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/qr/'),
        ),
    ]
